aws:
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
twitter:
  key: <%= Rails.application.credentials.dig(:twitter, :key) %>
  secret_key: <%= Rails.application.credentials.dig(:twitter, :secret_key) %>
  callback_url: 'https://spike-list.work/oauth/callback?provider=twitter'