twitter:
  key: <%= Rails.application.credentials.dig(:twitter, :key) %>
  secret_key: <%= Rails.application.credentials.dig(:twitter, :secret_key) %>
  callback_url: 'https://soccer-player-spikes.work/oauth/callback?provider=twitter'